/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class InicioPage1 extends javax.swing.JFrame {

    /**
     * Creates new form InicioPage1
     */
    public InicioPage1() {
        initComponents();
        setComponentPropertie1();
    }
    
    public final void setComponentPropertie1(){
        ImageIcon logo1 = new ImageIcon("bell-regular.png");
        ImageIcon logo2 = new ImageIcon("circle-user-regular.png");
        ImageIcon logo3 = new ImageIcon("house-solid.png");
        lblIconoNotificaciones.setText("");
        lblIconoNotificaciones.setIcon(logo1);
        lblIconoNotificaciones.setBounds(50, 50, lblIconoNotificaciones.getPreferredSize().width, lblIconoNotificaciones.getPreferredSize().height);  
        lblIconoPerfil.setText("");
        lblIconoPerfil.setIcon(logo2);
        lblIconoPerfil.setBounds(50, 50, lblIconoPerfil.getPreferredSize().width, lblIconoPerfil.getPreferredSize().height); 
        lblIconoCasita.setText("");
        lblIconoCasita.setIcon(logo3);
        lblIconoCasita.setBounds(50, 50, lblIconoCasita.getPreferredSize().width, lblIconoCasita.getPreferredSize().height); 
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWhiteBackground = new javax.swing.JPanel();
        pnlNavTab = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lblNoticiasEventos = new javax.swing.JLabel();
        lblMisFiguras = new javax.swing.JLabel();
        lblRecomendaciones = new javax.swing.JLabel();
        lblIconoNotificaciones = new javax.swing.JLabel();
        lblIconoPerfil = new javax.swing.JLabel();
        lblIconoCasita = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 830));
        setMinimumSize(new java.awt.Dimension(1280, 830));
        setPreferredSize(new java.awt.Dimension(1280, 830));
        setResizable(false);

        pnlWhiteBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlWhiteBackground.setPreferredSize(new java.awt.Dimension(1280, 830));
        pnlWhiteBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavTab.setBackground(new java.awt.Color(1, 22, 39));
        pnlNavTab.setMaximumSize(new java.awt.Dimension(1280, 100));
        pnlNavTab.setMinimumSize(new java.awt.Dimension(1280, 100));
        pnlNavTab.setPreferredSize(new java.awt.Dimension(1280, 100));

        jTextField1.setBackground(new java.awt.Color(1, 22, 39));
        jTextField1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(226, 226, 226));
        jTextField1.setText("Buscar figuras");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lblNoticiasEventos.setBackground(new java.awt.Color(1, 22, 39));
        lblNoticiasEventos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNoticiasEventos.setForeground(new java.awt.Color(255, 255, 255));
        lblNoticiasEventos.setText("Noticias y Eventos");
        lblNoticiasEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblMisFiguras.setBackground(new java.awt.Color(1, 22, 39));
        lblMisFiguras.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMisFiguras.setForeground(new java.awt.Color(255, 255, 255));
        lblMisFiguras.setText("Mis Figuras");
        lblMisFiguras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblRecomendaciones.setBackground(new java.awt.Color(1, 22, 39));
        lblRecomendaciones.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblRecomendaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblRecomendaciones.setText("Recomendaciones");
        lblRecomendaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblIconoNotificaciones.setText("jLabel4");
        lblIconoNotificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblIconoPerfil.setText("jLabel5");
        lblIconoPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblIconoCasita.setText("jLabel6");
        lblIconoCasita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlNavTabLayout = new javax.swing.GroupLayout(pnlNavTab);
        pnlNavTab.setLayout(pnlNavTabLayout);
        pnlNavTabLayout.setHorizontalGroup(
            pnlNavTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblIconoCasita)
                .addGap(26, 26, 26)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNoticiasEventos)
                .addGap(18, 18, 18)
                .addComponent(lblMisFiguras)
                .addGap(18, 18, 18)
                .addComponent(lblRecomendaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIconoNotificaciones)
                .addGap(18, 18, 18)
                .addComponent(lblIconoPerfil)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlNavTabLayout.setVerticalGroup(
            pnlNavTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavTabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlNavTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoticiasEventos)
                    .addComponent(lblMisFiguras)
                    .addComponent(lblRecomendaciones)
                    .addComponent(lblIconoNotificaciones)
                    .addComponent(lblIconoPerfil)
                    .addComponent(lblIconoCasita))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnlWhiteBackground.add(pnlNavTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        lblInicio.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(179, 179, 179));
        lblInicio.setText("Busca el nombre de una figura para intercambiar");
        pnlWhiteBackground.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlWhiteBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlWhiteBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblIconoCasita;
    private javax.swing.JLabel lblIconoNotificaciones;
    private javax.swing.JLabel lblIconoPerfil;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblMisFiguras;
    private javax.swing.JLabel lblNoticiasEventos;
    private javax.swing.JLabel lblRecomendaciones;
    private javax.swing.JPanel pnlNavTab;
    private javax.swing.JPanel pnlWhiteBackground;
    // End of variables declaration//GEN-END:variables
}
